version: '3'

services:
  postgresdev:
        image: postgres:9.5
        ports:
         - "5432:5434"
        environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=postgres
         - POSTGRES_DB=pgdev